### ISSUE TITLE
Improve services configurability 

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#24]
Currently we have quite a bunch of needed hosts and their related data, such as username, password and so on. While we do have some of the variables extracted, we need some more configurables.

Here's a list of all the services running:

- mongodb/rocksdb
  - [x] host
  - [x] database
- elasticsearch
  - [ ] host
- redis
  - [ ] host
- sidekiq (listed separately, as it will be a separate container)
  - [ ] host

Ideally, we'd end up with something like a YAML file containing the values for all the environments we have. I took the liberty to sketch it out a bit for the Mongoid bits:

```yaml
default: &default
  clients:
    default:
      options:
        read:
          mode: :primary
        max_pool_size: 1

development:
  <<: *default
  clients:
    default:
      database: elvis_development
      hosts:
        - localhost:27017

test:
  <<: *default
  clients:
    default:
      database: elvis_test
      hosts:
        - localhost:27017

production:
  <<: *default
  clients:
    default:
      database: elvis_production
      hosts:
        - localhost:27017
```

If making it a unified file proves to be a pain in the rear end, we could also do with the three env files. The main point of this is to extract the missing configurables so we could split the app on more hosts (dockerize, that is).
